name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Python 3.11 ist empfohlen (3.12 hat viele Kompatibilitätsprobleme mit ML-Libraries)
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Optional: pip cache leeren
      - name: Clear pip cache
        run: pip cache purge

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Deine weiteren Test- oder Build-Schritte...
      - name: Run Streamlit app test
        run: streamlit run app/app.py --server.headless true
