name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          # SpaCy Modell sicherstellen
          python - <<'PY'
          try:
              import spacy
              spacy.load("de_core_news_sm")
          except Exception:
              import subprocess, sys
              subprocess.check_call([sys.executable, "-m", "spacy", "download", "de_core_news_sm"])
          PY

      - name: Run tests
        run: pytest -q
