name: Deploy to Hugging Face

on:
  push:
    branches: ["main"]
    paths:
      - ".github/workflows/deploy.yml"
      - "app.py"
      - "api.py"
      - "src/**"
      - "presets/**"
      - "data/sample_corpus.json"
      - "requirements.txt"
      - "requirements-dev.txt"
      - "README.md"
      - "sitecustomize.py"
      - "scripts/deploy_to_hf.py"
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

env:
  HF_TOKEN: ${{ secrets.HF_TOKEN }}
  HF_SPACE_ID: ${{ secrets.HF_SPACE_ID }}
  HF_HEALTH_URL: ${{ secrets.HF_HEALTH_URL }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Validate required secrets
        id: secrets
        run: |
          missing=false
          for key in HF_TOKEN HF_SPACE_ID; do
            if [ -z "${!key:-}" ]; then
              echo "::warning::Missing secret ${key}"
              missing=true
            fi
          done
          echo "missing=$missing" >> "$GITHUB_OUTPUT"

      - name: Abort (missing secrets)
        if: steps.secrets.outputs.missing == 'true'
        run: |
          echo "Deployment skipped: configure HF_TOKEN and HF_SPACE_ID repository secrets."

      - uses: actions/checkout@v4
        if: steps.secrets.outputs.missing == 'false'

      - name: Set up Python
        if: steps.secrets.outputs.missing == 'false'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deployment dependencies
        if: steps.secrets.outputs.missing == 'false'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "huggingface_hub[cli]"

      - name: Deploy to Hugging Face Space
        if: steps.secrets.outputs.missing == 'false'
        env:
          HF_TOKEN: ${{ env.HF_TOKEN }}
          HF_SPACE_ID: ${{ env.HF_SPACE_ID }}
          HF_HEALTH_URL: ${{ env.HF_HEALTH_URL }}
        run: python scripts/deploy_to_hf.py
