name: Deploy

on:
  push:
    branches: ["main"]
    paths:
      - "app/**"
      - "requirements.txt"
      - "README.md"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "huggingface_hub[cli]" requests

      - name: Deploy to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          HF_SPACE_ID: ${{ secrets.HF_SPACE_ID }}
        run: |
          if [ -z "$HF_TOKEN" ] || [ -z "$HF_SPACE_ID" ]; then
            echo "HF_TOKEN and HF_SPACE_ID secrets must be configured."
            exit 1
          fi
          python - <<'PY'
import os
from datetime import datetime, timezone
from huggingface_hub import HfApi

token = os.environ["HF_TOKEN"]
space_id = os.environ["HF_SPACE_ID"]

api = HfApi(token=token)
api.upload_folder(
    folder_path=".",
    repo_id=space_id,
    repo_type="space",
    path_in_repo=".",
    commit_message=f"CI deploy ({datetime.now(timezone.utc).isoformat(timespec='seconds')})",
    allow_patterns=[
        "app/**",
        "src/**",
        "requirements*.txt",
        "README.md",
        "assets/**",
        "data/sample_corpus.json",
        "presets/**",
    ],
    ignore_patterns=[
        ".git/**",
        ".github/**",
        "notebooks/**",
        "tests/**",
        "docs/**",
    ],
)
PY

      - name: Health check
        if: ${{ secrets.HF_SPACE_ID != '' }}
        env:
          HF_SPACE_ID: ${{ secrets.HF_SPACE_ID }}
        run: |
          curl --fail --silent --show-error "https://huggingface.co/spaces/${HF_SPACE_ID}"
