name: Sync Topics

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  metadata: write

jobs:
  update-topics:
    runs-on: ubuntu-latest
    steps:
      - name: Set repository topics
        uses: actions/github-script@v7
        with:
          script: |
            const desiredTopics = ["audio-processing", "semantic-search", "streamlit"];
            await github.request("PUT /repos/{owner}/{repo}/topics", {
              owner: context.repo.owner,
              repo: context.repo.repo,
              names: desiredTopics,
              mediaType: {
                previews: ["mercy"]
              }
            });
